name: Test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_keyboard_visibility: ^5.0.3
  freezed_annotation: ^1.1.0
  responsive_builder: ^0.4.2
  package_info_plus: ^1.4.3
  hexcolor: ^2.0.7
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.15
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: 2.0.1
  freezed: ^1.1.1
  assets_indexer: ^0.0.10
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

